language: node_js
node_js:
  - "6"
addons:
    chrome: stable
before_install:
  - npm install -g karma-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start